language: node_js
node_js: node
script: 
- node fetch
- node compile
branches:
  except:
  - master # the master branch is used for deployment, if not ignored, will cause infinite CI loop
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  target-branch: master
  on:
    branch: dev
